### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by mcastorena0316**
We think we finished with our project, we put the knowledge we acquire today about forms, and did the page as similar as we could. Hope you can review it. Thanks

### CODE REVIEW

**Comment by KaushikShivam** [comment]
## Pull Request under the review of Shivam Kaushik

**Review by KaushikShivam — CHANGES_REQUESTED** [review]
# Changes Required 😈 

Hello, @mcastorena0316 & @ermin-cahtarevic. Nice to see you guys again 👋 
Awesome job for this project as well! I like the speed at which you guys are progressing. 👍 

However, there are a couple of things that are missing that I'd like you to do for this review to pass.

## Mandatory changes
1. Please make sure that you pass all the linter check
2. Descriptive README
    Make use of markdown to give more structure to the file. You can use this [tutorial](https://guides.github.com/features/mastering-markdown/) for reference. Things you can consider adding to your readme:
     - [ ] Author names and contact info
     - [ ] Live version of the website
     - [ ] Reference link of the youtube page and project guidelines 
3. Intuit products section
     - [ ] It should show the Mint logo and text (logo on the left, text on the right).
     - [ ] It should show the Quickbooks logo and text (logo on the left, text on the right). 
     - [ ] It should show the Turbotax logo and text (logo on the left, text on the right).
4. Intuit form
    - [ ] It should have a ```Learn More``` link.
5. The disclaimer text should have ```Terms``` and ```Privacy Statement``` as links
6. The footer should contain copyright and address information.
7. The password ```<input>``` should have a type of ```password``` instead of ```text```

 ### That's all, guys! 
**Make these changes and submit for a code review, again**

**If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**

Happy coding! 😄 
[Shivam Kaushik](https://github.com/KaushikShivam)
[Github](https://github.com/KaushikShivam) [Twitter](https://twitter.com/kShivamDev) [Linkedin](https://www.linkedin.com/in/shivam-kaushik-bb8162102/)

**Comment by mcastorena0316** [comment]
Hi, i think we already make all the changes you recommend, and also we already passed the lint test. We are ready for a new review.

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @mcastorena0316  and @ermin-cahtarevic :wave: 

You guys are doing great, let's attend to this remaining issue already pointed out.

- [ ] Your README is still umm.. unprofessional :wink: . You can refer to [this template](https://github.com/othneildrew/Best-README-Template) for a more pictorial guide.


**Please submit another code review request afterwards**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by ermin-cahtarevic** [comment]
We fixed the README file as you suggested and we used the template you recommended. We hope it is the final version now.

**Comment by shshamim63** [comment]
### Status: Approved.
___
Hi @mcastorena0316  & @ermin-cahtarevic  :wave:,
Well done :clap:, You have successfully completed this project. Nice and clean UI as like the original one. In one word you have nailed it.
This is from me :+1:. You can now merge the project and don't forget to fill the project submission form. Best of luck for your next project  
___
##### Happy Coding 
##### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Pull request merged**
